# Generated by Django 5.2 on 2025-04-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="description",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
